/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author leandro
 */
public class TabelaPrecos extends javax.swing.JDialog {

    /**
     * Creates new form TabelaPrecos
     */
    public TabelaPrecos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        URL url = this.getClass().getResource("/imgs/pingoAgua.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url).getScaledInstance(32, 32, Image.SCALE_SMOOTH);
        this.setIconImage(iconeTitulo);
        
        //Estilização
        tabelaPrecoAgua.getTableHeader().setFont(new Font("Candara", 1, 16));
        tabelaPrecoAgua.getTableHeader().setOpaque(false);
        tabelaPrecoEsgoto.getTableHeader().setFont(new Font("Candara", 1, 16));
        tabelaPrecoEsgoto.getTableHeader().setOpaque(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(0);
        ((DefaultTableCellRenderer)tabelaPrecoAgua.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(0);
        tabelaPrecoAgua.setDefaultRenderer(String.class, centerRenderer);
        ((DefaultTableCellRenderer)tabelaPrecoEsgoto.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(0);
        tabelaPrecoEsgoto.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPrecoAgua = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrecoEsgoto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Preço");

        tabelaPrecoAgua.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabelaPrecoAgua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "0 a 10", "26,18 (Preço fixo)"},
                {null, "11 a 20", "3,65/m³"},
                {"Residencial", "21 a 30", "5,61/m³"},
                {null, "31 a 50", "5,61/m³"},
                {null, "50+", "6,71/m³"}
            },
            new String [] {
                "Categoria", "Consumo (m³/mês)", "Valor (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPrecoAgua.setFocusable(false);
        tabelaPrecoAgua.setGridColor(new java.awt.Color(125, 125, 125));
        tabelaPrecoAgua.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaPrecoAgua.setRowHeight(25);
        tabelaPrecoAgua.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tabelaPrecoAgua.setShowVerticalLines(false);
        tabelaPrecoAgua.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaPrecoAgua);
        tabelaPrecoAgua.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tabelaPrecoAgua.getColumnModel().getColumnCount() > 0) {
            tabelaPrecoAgua.getColumnModel().getColumn(0).setResizable(false);
            tabelaPrecoAgua.getColumnModel().getColumn(1).setResizable(false);
            tabelaPrecoAgua.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Tarifas de água", jPanel1);

        tabelaPrecoEsgoto.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        tabelaPrecoEsgoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "0 a 10", "21,00 (Preço fixo)"},
                {null, "11 a 20", "2,88/m³"},
                {"Residencial", "21 a 30", "4,48/m³"},
                {null, "31 a 50", "4,48/m³"},
                {null, "50+", "5,34/m³"}
            },
            new String [] {
                "Categoria", "Consumo (m³/mês)", "Valor (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPrecoEsgoto.setFocusable(false);
        tabelaPrecoEsgoto.setGridColor(new java.awt.Color(125, 125, 125));
        tabelaPrecoEsgoto.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaPrecoEsgoto.setRowHeight(25);
        tabelaPrecoEsgoto.setSelectionBackground(new java.awt.Color(0, 153, 204));
        tabelaPrecoEsgoto.setShowVerticalLines(false);
        tabelaPrecoEsgoto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaPrecoEsgoto);
        tabelaPrecoEsgoto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tabelaPrecoEsgoto.getColumnModel().getColumnCount() > 0) {
            tabelaPrecoEsgoto.getColumnModel().getColumn(0).setResizable(false);
            tabelaPrecoEsgoto.getColumnModel().getColumn(1).setResizable(false);
            tabelaPrecoEsgoto.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Tarifas de esgoto", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaPrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaPrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaPrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaPrecos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TabelaPrecos dialog = new TabelaPrecos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaPrecoAgua;
    private javax.swing.JTable tabelaPrecoEsgoto;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
